<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--
    Each target framework is testing against a specific target framework of Dokan.
    
    To be able to test net4.0, we have to use net4.5 (the lowest supported framework by MSTest).
    -->
    <TargetFrameworks>net48;net9.0-windows</TargetFrameworks>
    
    <!--Add the Target Framework to the output file names. -->
    <AssemblyName>$(MSBuildProjectName).$(TargetFramework)</AssemblyName>
    <CLSCompliant>True</CLSCompliant>
    <!-- We need to sign the test assembly to use it in InternalsVisibleTo for DokanNet.dll. -->
    <SignAssembly>false</SignAssembly>
    <AssemblyOriginatorKeyFile>..\DokanNet\Dokan.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ContextTests.cs" />
    <Compile Remove="DirectoryInfoTest.cs" />
    <Compile Remove="DokanOperationsFixture.cs" />
    <Compile Remove="DriveInfoTests.cs" />
    <Compile Remove="FileInfoTests.cs" />
    <Compile Remove="Mounter.cs" />
    <Compile Remove="OverlappedTests.cs" />
    <Compile Remove="StringExtensions.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="OverlappedTests.Configuration.xml">
      <DependentUpon>OverlappedTests.cs</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
    <PackageReference Include="Moq" Version="4.*" />
    <PackageReference Include="MSTest.TestAdapter" Version="*" />
    <PackageReference Include="MSTest.TestFramework" Version="2.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DokanNet\DokanNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
